//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acCajaAhorro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acCajaAhorro()
        {
            this.acDetalleCajaAhorro = new HashSet<acDetalleCajaAhorro>();
        }
    
        public int iCajaAhorro_id { get; set; }
        public string sCajaAhorro_num { get; set; }
        public int iTipoCaja_fl { get; set; }
        public int iMoneda_fl { get; set; }
        public decimal dCajaAhorro_saldo { get; set; }
        public decimal dCajaAhorro_montoMaximoRetiro { get; set; }
        public int iEstadoCajaAhorro_fl { get; set; }
        public int iCliente_id { get; set; }
        public int iTarjetaDebito_id { get; set; }
    
        public virtual peCliente peCliente { get; set; }
        public virtual acTarjetaDebito acTarjetaDebito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acDetalleCajaAhorro> acDetalleCajaAhorro { get; set; }
    }
}
