//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acDetalleDPF
    {
        public int iDetalleDPF_id { get; set; }
        public int iDPF_id { get; set; }
        public int iTipoTransaccionDPF { get; set; }
        public decimal dDetalleDPF_monto { get; set; }
        public System.DateTime dtDetalleDPF_fecha { get; set; }
        public string sDetalleDPF_desc { get; set; }
        public int iTransaccion_id { get; set; }
    
        public virtual acDPF acDPF { get; set; }
        public virtual mcTransaccion mcTransaccion { get; set; }
    }
}
