//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acDPF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acDPF()
        {
            this.acDetalleDPF = new HashSet<acDetalleDPF>();
        }
    
        public int iDPF_id { get; set; }
        public System.DateTime dtDPF_fechaInicio { get; set; }
        public int iDuracionDPF_fl { get; set; }
        public System.DateTime dtDPF_fechaCaducidad { get; set; }
        public decimal dDPF_interes { get; set; }
        public decimal dDPF_monto { get; set; }
        public int iEstadoDPF_fl { get; set; }
        public int iCliente_id { get; set; }
    
        public virtual peCliente peCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acDetalleDPF> acDetalleDPF { get; set; }
    }
}
