//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acTarjetaDebito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acTarjetaDebito()
        {
            this.acCajaAhorro = new HashSet<acCajaAhorro>();
        }
    
        public int iTarjetaDebito_id { get; set; }
        public string sTarjetaDebito_num { get; set; }
        public string sTarjetaDebito_cvc { get; set; }
        public string iTarjetaDebito_PIN { get; set; }
        public int iCliente_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acCajaAhorro> acCajaAhorro { get; set; }
        public virtual peCliente peCliente { get; set; }
    }
}
