//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class baAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public baAdmin()
        {
            this.baUnidadFinanciera = new HashSet<baUnidadFinanciera>();
        }
    
        public int iAdmin_id { get; set; }
        public string sAdmin_nm { get; set; }
        public string sAdmin_apell { get; set; }
        public int iADM_USER_id { get; set; }
        public string iAdmin_funcionfl { get; set; }
    
        public virtual baADM_USER baADM_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<baUnidadFinanciera> baUnidadFinanciera { get; set; }
    }
}
