//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class baUnidadFinanciera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public baUnidadFinanciera()
        {
            this.baModulo = new HashSet<baModulo>();
            this.paSucursal = new HashSet<paSucursal>();
        }
    
        public int iUnidadFinanciera_id { get; set; }
        public string sUnidadFinanciera_nm { get; set; }
        public string sUnidadFinanciera_NIT { get; set; }
        public string sUnidadFinanciera_dir { get; set; }
        public string sUnidadFinanciera_telf { get; set; }
        public string sUnidadFinanciera_desc { get; set; }
        public int iUnidadFinanciera_cantSuc { get; set; }
        public int iAdmin_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<baModulo> baModulo { get; set; }
        public virtual baAdmin baAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paSucursal> paSucursal { get; set; }
    }
}
