//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coCouta
    {
        public int iCuota_id { get; set; }
        public int iSolicitudCredito_id { get; set; }
        public decimal dCuota_capital { get; set; }
        public decimal dCuota_interes { get; set; }
        public string sCuota_num { get; set; }
        public string sCuota_monto { get; set; }
        public short iMoneda_fl { get; set; }
        public System.DateTime dtCuota_fecha { get; set; }
    
        public virtual coCredito coCredito { get; set; }
    }
}
