//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coRequisito
    {
        public int iRequisito_id { get; set; }
        public int iSolicitudCredito_id { get; set; }
        public string sRequisito_desc { get; set; }
        public string sRequisito_estado { get; set; }
        public short iRequisito_importancia { get; set; }
    
        public virtual coSolicitudCredito coSolicitudCredito { get; set; }
    }
}
