//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coSolicitudCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coSolicitudCredito()
        {
            this.coRequisito = new HashSet<coRequisito>();
        }
    
        public int iSolicitudCredito_id { get; set; }
        public System.DateTime dtSolicitudCredito_fecha { get; set; }
        public short iTipoCredito_fl { get; set; }
        public decimal dSolicitudCredito_monto { get; set; }
        public short iMoneda_fl { get; set; }
        public short iPlazoCredito_fl { get; set; }
        public decimal dInteresAnual { get; set; }
        public int iCliente_id { get; set; }
        public int iUsuario_id { get; set; }
        public Nullable<int> iSolicitudCredito_discriminador { get; set; }
        public int iSolicitudCredito_estado { get; set; }
    
        public virtual peSocio peSocio { get; set; }
        public virtual msUsuario msUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coRequisito> coRequisito { get; set; }
    }
}
