//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mcLibroCaja
    {
        public int iLibroCaja_id { get; set; }
        public Nullable<int> iTransaccion_id { get; set; }
        public string dtLibroCaja_fecha { get; set; }
        public string iCaja_id { get; set; }
        public decimal dDebe_mn { get; set; }
        public decimal dDebe_me { get; set; }
        public decimal dHaber_mn { get; set; }
        public decimal dHaber_me { get; set; }
        public decimal dSaldo_mn { get; set; }
        public decimal dSaldo_me { get; set; }
        public Nullable<int> iSolicitudFondo_id { get; set; }
    
        public virtual mcTransaccion mcTransaccion { get; set; }
        public virtual teSolicitudFondo teSolicitudFondo { get; set; }
    }
}
