//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msBitacora
    {
        public int iBitadora_id { get; set; }
        public string dtBitacora_fechaRegistro { get; set; }
        public string iUsuario_id { get; set; }
        public string sBitacora_desc { get; set; }
        public string sTablaModificada { get; set; }
        public string sOperacionRealizada { get; set; }
    }
}
