//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msFuncionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msFuncionario()
        {
            this.msUsuario = new HashSet<msUsuario>();
        }
    
        public int iFuncionario_id { get; set; }
        public string sFuncionario_nombre { get; set; }
        public string sFuncionario_apellido { get; set; }
        public string sFuncionario_ci { get; set; }
        public System.DateTime dtFuncionario_fechaContratacion { get; set; }
        public string sFuncionario_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msUsuario> msUsuario { get; set; }
    }
}
