//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msPassword
    {
        public int iPassword_id { get; set; }
        public System.DateTime dtPassword_fechaCambio { get; set; }
        public string sPassword_anterior { get; set; }
        public int iUsuario_id { get; set; }
    
        public virtual msUsuario msUsuario { get; set; }
    }
}
