//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msUsuario()
        {
            this.msPassword = new HashSet<msPassword>();
            this.mcCaja = new HashSet<mcCaja>();
            this.caPAC = new HashSet<caPAC>();
            this.coSolicitudCredito = new HashSet<coSolicitudCredito>();
        }
    
        public int iUsuario_id { get; set; }
        public string sUsuario_username { get; set; }
        public string sUsuario_password { get; set; }
        public int iFuncionario_id { get; set; }
        public int iRol_id { get; set; }
    
        public virtual msFuncionario msFuncionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msPassword> msPassword { get; set; }
        public virtual msRol msRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mcCaja> mcCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caPAC> caPAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coSolicitudCredito> coSolicitudCredito { get; set; }
    }
}
