//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oaATM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oaATM()
        {
            this.mcTransaccion = new HashSet<mcTransaccion>();
            this.oaTarjetaRetenida = new HashSet<oaTarjetaRetenida>();
        }
    
        public int iATM_id { get; set; }
        public string sATM_fabrica { get; set; }
        public string sATM_dir { get; set; }
        public short iATM_tipo { get; set; }
        public string sATM_nombre { get; set; }
        public System.DateTime dtATM_ultimaConciliacion { get; set; }
        public int iATM_estado { get; set; }
        public decimal dATM_saldoMN { get; set; }
        public decimal dATM_saldoME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mcTransaccion> mcTransaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oaTarjetaRetenida> oaTarjetaRetenida { get; set; }
    }
}
