//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oaLibroATM
    {
        public int oaLibroATM_id { get; set; }
        public System.DateTime dtLibroATM_fecha { get; set; }
        public decimal dDebe_mn { get; set; }
        public decimal dDebe_me { get; set; }
        public decimal dHaber_mn { get; set; }
        public decimal dHaber_me { get; set; }
        public decimal dSaldo_mn { get; set; }
        public decimal dSaldo_me { get; set; }
        public string sLibroATM_desc { get; set; }
        public int iAtm_id { get; set; }
        public int iTransaccion_id { get; set; }
    
        public virtual mcTransaccion mcTransaccion { get; set; }
    }
}
