//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oaTarjetaRetenida
    {
        public int iTarjetaRetenida_id { get; set; }
        public System.DateTime dtRetenida_fecha { get; set; }
        public string sTarjetaDebito_num { get; set; }
        public string sRetenida_desc { get; set; }
        public int iATM_id { get; set; }
    
        public virtual oaATM oaATM { get; set; }
    }
}
