//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paSucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paSucursal()
        {
            this.caPAC = new HashSet<caPAC>();
            this.mcCaja = new HashSet<mcCaja>();
            this.teBoveda = new HashSet<teBoveda>();
        }
    
        public int iSucursal_id { get; set; }
        public string sSucursal_nm { get; set; }
        public string sSucursal_dir { get; set; }
        public string sSucursal_telf { get; set; }
        public int iSucursal_cantCajas { get; set; }
        public int iUnidadFinanciera_id { get; set; }
    
        public virtual baUnidadFinanciera baUnidadFinanciera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caPAC> caPAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mcCaja> mcCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teBoveda> teBoveda { get; set; }
    }
}
