//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teBoveda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teBoveda()
        {
            this.teSolicitudFondo = new HashSet<teSolicitudFondo>();
            this.teConciliacionLM = new HashSet<teConciliacionLM>();
        }
    
        public int iBoveda_id { get; set; }
        public decimal dBoveda_montoActualMN { get; set; }
        public decimal dBoveda_montoActualME { get; set; }
        public System.DateTime dtBoveda_ultimaConciliacion { get; set; }
        public int iSucursal_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teSolicitudFondo> teSolicitudFondo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teConciliacionLM> teConciliacionLM { get; set; }
        public virtual paSucursal paSucursal { get; set; }
    }
}
