//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSIGEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teConciliacionLM
    {
        public int iConciliacionLM_id { get; set; }
        public int iBoveda_id { get; set; }
        public decimal dDebe_mn { get; set; }
        public decimal dDebe_me { get; set; }
        public decimal dHaber_mn { get; set; }
        public decimal dHaber_me { get; set; }
        public decimal dSaldo_mn { get; set; }
        public decimal dSaldo_me { get; set; }
        public System.DateTime dtConciliacionLM_fecha { get; set; }
    
        public virtual teBoveda teBoveda { get; set; }
    }
}
